### ISSUE TITLE
Why these deps in Editor example

### ISSUE THREAD

**Issue by linonetwo** [FlydeHQ/flyde#30]
I'm learning the usage from the code, here are something not clear:

Why is 

```
      extraContext: {
        PubSub,
      },
``` 

https://github.com/FlydeHQ/flyde/blob/a3da13b5d25d6bbb2356ff6c0d04d593b2f35767/website/src/components/EmbeddedFlyde/EmbeddedFlyde.tsx#L2

this seem to not use elsewhere?

Answer: used in `Publish` node

But why not let nodes come with their own dependency, instead of let runtime provide for them?

---

and why is `import { fakeVm } from "@site/src/fake-vm";`, seems 

```
import {
  execute,
} from '@flyde/core';
```

can already do the code execution?

**Comment by linonetwo** [comment]
Thought flyde is lack of doc, but NoFlo is more complicated and no one can answer questions, so I decided to use flyde at the moment. @GabiGrin can you help me here?

**Comment by GabiGrin** [comment]
That’s actually a technical debt from a major change to Flyde. Flyde started as a cloud based “visual serverless” platform but I quickly realized it must start as an OS project.  Flows used to run in a vm2 instance on my servers, but when running on the client it wasn’t really necessary 

Regarding PubSub, leaving it to the context of the node means I can’t separate their execution and kinda breaks the whole modular design. The real solution here is to make it a first class citizen

wdyt?

The difference with pubshb

**Comment by GabiGrin** [comment]
Does that answer your questions? looking forward to your thoughts

**Comment by linonetwo** [comment]
OK, I can understand that. As long as i can publish other nodes in a self contained way.

I'm going to write some plugins providing nodes with dependency, and load them using esm/eval. Those dependences won't need to be provided by the host (flyde runtime)

**Comment by GabiGrin** [comment]
Ok, let me know if you need any help! Would love seeing Flyde being integrated in your project
