### ISSUE TITLE
Not visible in VSCodium :(

### ISSUE THREAD

**Issue by j2l** [FlydeHQ/flyde#7]
Looks cool but there's no vsx realease nor VSCodium (VSCode without telemetry) extension.

**Comment by GabiGrin** [comment]
hey @j2l  sorry missed that! still in "pre release" stage so didn't think there would be issues already 😊 
The extension is open source as well - https://github.com/FlydeHQ/flyde-vscode and contains the VSX files used to release versions so far.
I'll take a look at releasing it to VSCodium as well, thanks for showing interest!
