### ISSUE TITLE
examples: parallel map

### ISSUE THREAD

**Issue by francescoagati** [FlydeHQ/flyde#8]
hi,
there is an example of parallel map node implementation?

something like this https://flows.nodered.org/node/node-red-contrib-wait-paths

**Comment by GabiGrin** [comment]
Hey @francescoagati, I've made many improvements to the extension since, and one of them being a few templates to choose from, one of them looping through the responses of 2 API calls and merging them into a new object:

![Kapture 2023-04-17 at 22 26 19](https://user-images.githubusercontent.com/3727015/232590680-c8706826-b55b-4c47-81e0-e0626cc83cc7.gif)

If you try it, let me know what you think!

**Comment by francescoagati** [comment]
hey thanks,
 i have try but i get this error with a simple flow

ode_modules/@flyde/resolver/dist/resolver/resolve-dependencies/resolve-dependencies.js:37
    const refPartIds = part.instances
                            ^
TypeError: Cannot read property 'instances' of undefined

wutg tgus cide ++const {loadFlow} = require('@flyde/runtime');

const executeFlow = loadFlow('./hello.flyde');

executeFlow() // executeFlow can also receive inputs, and other advanced configuration, more on that in the next steps
    .then(({message}) => console.log(message))

**Comment by GabiGrin** [comment]
Hey @francescoagati, thanks for trying out that quick!
Please try:
```
const {loadFlowByPath} = require('@flyde/runtime');
const executeFlow = export function loadFlowByPath<Inputs>(
('./hello.flyde');
```
Docs need some update after the latest major refactoring :) 

Also, `.then(({message}) => console.log(message))`.  won't work.
You can try:
```
const executeFlow = loadFlowByPath('hello.flyde');
const result  = executeFlow({} ,{
    onOutputs: (outputs,data) => {
        console.log('............')
        console.log(outputs);
        console.log(data);

    }
})
```
Flyde required users to explicitly say what output pins cause the part to be completed (see https://www.flyde.dev/docs/lifecycle/). I've now added implicit completion, which the templates use, but it broke the output generation. Going to fix that soon!

**Comment by GabiGrin** [comment]
@francescoagati forgot to update that a fix was published


looking forward for your feedback and thanks for the patience in such an early stage of the project :)
